2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_setup.py:_flush():67] Configure stats pid to 3692
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_setup.py:_flush():67] Loading settings from C:\Users\DELL\.config\wandb\settings
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_setup.py:_flush():67] Loading settings from c:\Users\DELL\Desktop\Coding\Python\DL\wandb\settings
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010205-ezwllfxq\logs\debug.log
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\DELL\Desktop\Coding\Python\DL\wandb\run-20250301_010205-ezwllfxq\logs\debug-internal.log
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000021AF22BB820>
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:init():761] calling init triggers
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:init():784] starting backend
2025-03-01 01:02:05,171 INFO    MainThread:3692 [wandb_init.py:init():788] sending inform_init request
2025-03-01 01:02:05,182 INFO    MainThread:3692 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-01 01:02:05,183 INFO    MainThread:3692 [wandb_init.py:init():803] backend started and connected
2025-03-01 01:02:05,185 INFO    MainThread:3692 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-01 01:02:05,186 INFO    MainThread:3692 [wandb_init.py:init():896] updated telemetry
2025-03-01 01:02:05,220 INFO    MainThread:3692 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-01 01:02:07,106 INFO    MainThread:3692 [wandb_init.py:init():995] starting run threads in backend
2025-03-01 01:02:07,417 INFO    MainThread:3692 [wandb_run.py:_console_start():2377] atexit reg
2025-03-01 01:02:07,417 INFO    MainThread:3692 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-01 01:02:07,417 INFO    MainThread:3692 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-01 01:02:07,417 INFO    MainThread:3692 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-01 01:02:07,419 INFO    MainThread:3692 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-01 01:02:07,420 INFO    MainThread:3692 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=50
2025-03-01 01:02:08,057 ERROR   MainThread:3692 [internal_api.py:execute():402] 404 response executing GraphQL.
2025-03-01 01:02:08,057 ERROR   MainThread:3692 [internal_api.py:execute():403] {"errors":[{"message":"could not find project bullseye2608-indian-institute-of-technology-madras/uncategorized during createAgent","path":["createAgent"]}],"data":{"createAgent":null}}
2025-03-01 01:02:08,238 INFO    MainThread:3692 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-01 01:02:08,238 INFO    MainThread:3692 [wandb_init.py:_pause_backend():564] pausing backend
